### PR TITLE
NSP bar

### PR DESCRIPTION
**Pull request by ivansg44**
Implemented NSP bar under gene bar

### CODE REVIEW

**Comment by ivansg44** [comment]
@anwarMZ Please review the proposed colour scheme in [``nsp_colors.json``](https://github.com/cidgoh/COVID-MVP/blob/fa190ab560ec632cb7ac09773beb719ff5ec7ad9/assets/nsp_colors.json)

**Review by anwarMZ — COMMENTED** [review]
I believe you have used 8-color palette that repeats itself in a different order. However, since NSPs don't have a "standardized/specific" colors attached to them like the SARS-CoV-2 genes through Nextstrain etc, I wonder if we should have different colors for NSPs at all or just have them all in same color e.g., [this figure](https://www.nature.com/articles/s41392-021-00653-w/figures/1) ? 

Otherwise, I suggest having distinct colors for all NSPs (I believe we can get 16 distinct colors pallete) just to avoid any confusion that any two NSPs are same colored for any biological reason.

**Comment by ivansg44** [comment]
16 distinct colour palette would not prevent much confusion, because it is generally difficult for visualization solutions to effectively distinguish that many unique colours. Just an FYI Nextstrain also uses some colours twice, which is what have in the gene bar.

However, I like the idea of only using distinct colours for genes, and monocolour for NSP. I’m going to implement that

**Comment by anwarMZ** [comment]
> Just an FYI Nextstrain also uses some colours twice, which is what have in the gene bar.

Yes,I am aware of that but because genes are more distinct as compared to NSPs. Especially in the case where NSPs can overlap for example NSP11 and NSP12. 

> However, I like the idea of only using distinct colours for genes, and monocolour for NSP. I’m going to implement that

Great, let me know once you have an image to review - if needed

**Pull request merged**
